### ISSUE TITLE
After upgrade to latest version on sandstorm platform, i met an issue.

### ISSUE THREAD

**Issue by eddyx** [synchrone/sandstorm-radicale#22] opened 2016-08-05 07:52 UTC
I can't modify or delete any information, in the log, i saw the following lines.

File "/opt/app/env/lib/python3.4/tempfile.py", line 538, in func_wrapper
    return func(*args, **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 137-139: ordinal not in range(128)

I am using Chinese letters as first name and last name etc. It worked well in previous version.

Please help to take a look at this issue. 

Thank you.

**Comment by keybits** [comment] 2016-08-05 10:17
I think I have a duplicate of this. After upgrade to latest version I cannot create new Contacts or edit existing conacts. On click Save I get:

```
Error unable to save the contact - Internal server error
```

This is on hosted Oasis.

**Comment by synchrone** [comment] 2016-08-05 10:28
Indeed, the current version does not handle UTF-8
```
Traceback (most recent call last):
  File "/opt/app/main.py", line 22, in __call__
    return self.radicale.__call__(environ, start_response)
  File "/opt/app/env/lib/python3.4/site-packages/radicale/__init__.py", line 332, in __call__
    user)
  File "/opt/app/env/lib/python3.4/site-packages/radicale/__init__.py", line 588, in do_PUT
    xmlutils.put(environ["PATH_INFO"], content, collection)
  File "/opt/app/env/lib/python3.4/site-packages/radicale/xmlutils.py", line 453, in put
    collection.append(name, ical_request)
  File "/opt/app/env/lib/python3.4/site-packages/radicale/ical.py", line 361, in append
    self.write()
  File "/opt/app/env/lib/python3.4/site-packages/radicale/ical.py", line 377, in write
    self.save(text)
  File "/opt/app/env/lib/python3.4/site-packages/radicale/storage/filesystem.py", line 101, in save
    fd.write(text)
  File "/opt/app/env/lib/python3.4/tempfile.py", line 538, in func_wrapper
    return func(*args, **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 209861-209871: ordinal not in range(128)
```

**Comment by keybits** [comment] 2016-08-05 10:31
Thanks for the quick reply. Ah the joys of character encoding!

What's the best way forward?

**Comment by synchrone** [comment] 2016-08-05 10:50
I'm tempted to rollback the v12 release from oasis, since I screwed up back-porting an upstream patch for issue #21.
Will be able to do it in 9 hours earliest.

**Comment by keybits** [comment] 2016-08-05 11:11
Sounds like a good plan. No rush. :-) Thanks for you work on this - very useful app.

**Comment by eddyx** [comment] 2016-08-05 14:27
Thank you for the reply.

**Comment by zeigerpuppy** [comment] 2016-08-06 01:51
same here, can't access contacts.

![2016-08-06 11 49 56 am](https://cloud.githubusercontent.com/assets/415981/17454017/008d9b4e-5bcc-11e6-8ace-2663094783d2.png)

**Comment by eddyx** [comment] 2016-08-06 12:18
Yes, that's also what i thought. If Sandstorm has the mechanism to rollback to previous version, it will be helpful to protect the data. I am nearly going to delete the app for i can't use it.

**Comment by synchrone** [comment] 2016-08-07 08:52
Ok, v13 was released yesterday. UTF-8 support is back, so I am closing this issue

**Closed by synchrone** 2016-08-07 08:52 UTC

**Comment by zeigerpuppy** [comment] 2016-08-08 01:30
thanks, working well

**Comment by eddyx** [comment] 2016-08-08 01:37
Thank you, will the new release be pushed by the sandstorm?

**Comment by synchrone** [comment] 2016-08-08 15:36
@eddyx you will need to click "Upgrade grains" in the usual Bell notification dropdown in the top bar.

**Comment by eddyx** [comment] 2016-08-09 02:41
It runs well now, thank you.
